package com.bwie.greendaodemo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bwie.greendaodemo.entity.CartEntity;
import com.bwie.greendaodemo.entity.ShoppingCartListBean;

import com.bwie.greendaodemo.greendao.CartEntityDao;
import com.bwie.greendaodemo.greendao.ShoppingCartListBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cartEntityDaoConfig;
    private final DaoConfig shoppingCartListBeanDaoConfig;

    private final CartEntityDao cartEntityDao;
    private final ShoppingCartListBeanDao shoppingCartListBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cartEntityDaoConfig = daoConfigMap.get(CartEntityDao.class).clone();
        cartEntityDaoConfig.initIdentityScope(type);

        shoppingCartListBeanDaoConfig = daoConfigMap.get(ShoppingCartListBeanDao.class).clone();
        shoppingCartListBeanDaoConfig.initIdentityScope(type);

        cartEntityDao = new CartEntityDao(cartEntityDaoConfig, this);
        shoppingCartListBeanDao = new ShoppingCartListBeanDao(shoppingCartListBeanDaoConfig, this);

        registerDao(CartEntity.class, cartEntityDao);
        registerDao(ShoppingCartListBean.class, shoppingCartListBeanDao);
    }
    
    public void clear() {
        cartEntityDaoConfig.clearIdentityScope();
        shoppingCartListBeanDaoConfig.clearIdentityScope();
    }

    public CartEntityDao getCartEntityDao() {
        return cartEntityDao;
    }

    public ShoppingCartListBeanDao getShoppingCartListBeanDao() {
        return shoppingCartListBeanDao;
    }

}
